### ISSUE TITLE
Save games of registered users

### ISSUE THREAD

**Issue by fmbenhassine** [benas/gamehub.io#2]
It is possible to play chess on chesshub.io as anonymous. Games played by anonymous players are not saved in the database. In contrast, when a registered user plays a game, the game should be persisted to the database and indexed in elastic search

**Comment by Cuong12** [comment]
Plz help me :( . How can i fix it ?

$ node initdata
Elasticsearch INFO: 2017-01-11T03:19:19Z
  Adding connection to http://localhost:9200/

Elasticsearch DEBUG: 2017-01-11T03:19:19Z
  starting request {
    "method": "HEAD",
    "requestTimeout": 5000,
    "castExists": true,
    "path": "/",
    "query": {}
  }


Elasticsearch DEBUG: 2017-01-11T03:19:19Z
  starting request {
    "method": "PUT",
    "path": "/chesshub",
    "query": {}
  }


(node:7088) DeprecationWarning: Mongoose: mpromise (mongoose's default promise l
ibrary) is deprecated, plug in your own promise library instead: http://mongoose
js.com/docs/promises.html
Elasticsearch TRACE: 2017-01-11T03:19:20Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch ERROR: 2017-01-11T03:19:20Z
  Error: Request error, retrying
  HEAD http://localhost:9200/ => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Users\MyPC\Desktop\gamehub.io-master\node_modules\elastic
search\src\lib\log.js:225:56)
      at checkRespForFailure (C:\Users\MyPC\Desktop\gamehub.io-master\node_modul
es\elasticsearch\src\lib\transport.js:240:18)
      at HttpConnector.<anonymous> (C:\Users\MyPC\Desktop\gamehub.io-master\node
_modules\elasticsearch\src\lib\connectors\http.js:162:7)
      at ClientRequest.wrapper (C:\Users\MyPC\Desktop\gamehub.io-master\node_mod
ules\elasticsearch\node_modules\lodash\lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Elasticsearch TRACE: 2017-01-11T03:19:20Z
  -> PUT http://localhost:9200/chesshub

  <- 0


Elasticsearch ERROR: 2017-01-11T03:19:20Z
  Error: Request error, retrying
  PUT http://localhost:9200/chesshub => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Users\MyPC\Desktop\gamehub.io-master\node_modules\elastic
search\src\lib\log.js:225:56)
      at checkRespForFailure (C:\Users\MyPC\Desktop\gamehub.io-master\node_modul
es\elasticsearch\src\lib\transport.js:240:18)
      at HttpConnector.<anonymous> (C:\Users\MyPC\Desktop\gamehub.io-master\node
_modules\elasticsearch\src\lib\connectors\http.js:162:7)
      at ClientRequest.wrapper (C:\Users\MyPC\Desktop\gamehub.io-master\node_mod
ules\elasticsearch\node_modules\lodash\lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Elasticsearch TRACE: 2017-01-11T03:19:21Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:21Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:21Z
  No living connections

elasticsearch is down!
Elasticsearch TRACE: 2017-01-11T03:19:21Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:21Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:21Z
  No living connections

Elasticsearch DEBUG: 2017-01-11T03:19:21Z
  starting request {
    "method": "POST",
    "path": "/chesshub/game/1/_create",
    "body": {
      "white": "Foo",
      "black": "Anonymous",
      "content": "1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. O-O Bc5 5. c3 O-O 6. d4 exd4
 7. cxd4 Bb4",
      "result": "1-0"
    },
    "query": {}
  }


Elasticsearch TRACE: 2017-01-11T03:19:22Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:22Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:22Z
  No living connections

Elasticsearch DEBUG: 2017-01-11T03:19:23Z
  starting request {
    "method": "POST",
    "path": "/chesshub/game/2/_create",
    "body": {
      "white": "Anonymous",
      "black": "Bar",
      "content": "1. e4 c6 2. e5 d5 3. exd6 exd6 4. Nf3 Bg4 5. d4 Nf6 6. Bg5 Be7
",
      "result": "1-0"
    },
    "query": {}
  }

**Comment by benas** [comment]
Hi @Cuong12 

I see "elasticsearch is down!" in these logs.

Is elastic search up and running?

Could you please open a separate issue? I'll look into it asap.

Thank you
Kind regards
Mahmoud
